### ISSUE TITLE
RFC files CLI

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-files-rest#128]
In Zenodo we currently have a custom file curation CLI implemented, specific to our usecases. It might be worthwhile to have something generic. This would be a good starting point, which at the moment would also satisfy our use cases:

`invenio files list [OPTIONS]`
`invenio files add <file> [OPTIONS]`
`invenio files remove <key> [OPTIONS]`
`invenio files rename <old_key> <new_key> [OPTIONS]`

In the end the commands needs to determine a bucket on which the operations are to be made, one obvious choice for [OPTIONS] would be:
`--bucket/-b <bucket UUID>`
however, one would also want to have a direct replacement on a record or deposit without dealing with UUIDs on the command line, e.g.:
`--recid/-r <recid>` or maybe better a pair `--type/-t <pid_type> --value/-v <pid_value>`, so that the following is also possible:

`invenio files add ./file.txt --recid 12345` or maybe pid_value-indifferent version:
`invenio files add ./file.txt -t recid -v 12345`

**Comment by jirikuncar** [comment]
> however, one would also want to have a direct replacement on a record or deposit

@krzysztof That part should go to `invenio-records-files`.

**Comment by krzysztof** [comment]
> however, one would also want to have a direct replacement on a record or deposit
@krzysztof That part should go to invenio-records-files.

@jirikuncar I agree. Can the CLI group name "files" be reused?

**Comment by jirikuncar** [comment]
> Can the CLI group name "files" be reused?

Yes, but you will need new subcommand. `invenio files record -t recid -v 12345 add ./file.txt -k mykey --extra '{"foo": "bar"}'

**Comment by krzysztof** [comment]
It would be also nice to include adding files directly from the URL, namely the ``<file>`` in ``invenio files add <file>`` could also be an URL which is fetched with a request. CDS has a similar function here: https://github.com/CERNDocumentServer/cds/blob/cdslabs_qa/cds/modules/webhooks/tasks.py#L110

**Comment by krzysztof** [comment]
Zenodo-specific implementation for reference: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/utils/cli.py#L64

**Comment by nharraud** [comment]
*As said during the Invenio Developer meeting:*
For B2Share we will in some case publish files which are already accessible on an IRODS filesystem. It would then make sense to be able to add/replace files with other files which are also already on IRODS.
=> In this case the `replace` and `add` commands would just be given the PyFilesystem URI. No file transfer would occur.

**Comment by mbhesam** [comment]
hello. when i want to check python dependencies with command (invenio-cli check-requirements --developments) , following error apear:
Traceback (most recent call last):
  File "/usr/local/bin/invenio-cli", line 8, in <module>
    sys.exit(invenio_cli())
  File "/home/hes/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hes/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hes/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hes/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hes/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/invenio_cli/cli/cli.py", line 53, in check_requirements
    run_steps(steps, on_fail, on_success)
  File "/usr/local/lib/python3.8/dist-packages/invenio_cli/cli/utils.py", line 21, in run_steps
    result = step.execute()
  File "/usr/local/lib/python3.8/dist-packages/invenio_cli/commands/steps.py", line 40, in execute
    response = self.func(**self.args)
  File "/usr/local/lib/python3.8/dist-packages/invenio_cli/commands/requirements.py", line 79, in check_node_version
    result = run_cmd(["node", "--version"])
  File "/usr/local/lib/python3.8/dist-packages/invenio_cli/helpers/process.py", line 34, in run_cmd
    p = popen(command, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'node'
